	.file	"main.cpp"
# GNU C++17 (Ubuntu 11.4.0-1ubuntu1~22.04.2) version 11.4.0 (x86_64-linux-gnu)
#	compiled by GNU C version 11.4.0, GMP version 6.2.1, MPFR version 4.1.0, MPC version 1.2.1, isl version isl-0.24-GMP

# GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
# options passed: -mtune=generic -march=x86-64 -O3 -fomit-frame-pointer -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection
	.text
	.p2align 4
	.globl	_Z5func1v
	.type	_Z5func1v, @function
_Z5func1v:
.LFB0:
	.cfi_startproc
	endbr64	
	subq	$8, %rsp	#,
	.cfi_def_cfa_offset 16
# main.cpp:3: int func1() { return other(233) + 1; }
	movl	$233, %edi	#,
	call	_Z5otheri@PLT	#
# main.cpp:3: int func1() { return other(233) + 1; }
	addq	$8, %rsp	#,
	.cfi_def_cfa_offset 8
# main.cpp:3: int func1() { return other(233) + 1; }
	addl	$1, %eax	#, tmp84
# main.cpp:3: int func1() { return other(233) + 1; }
	ret	
	.cfi_endproc
.LFE0:
	.size	_Z5func1v, .-_Z5func1v
	.p2align 4
	.globl	_Z5func2v
	.type	_Z5func2v, @function
_Z5func2v:
.LFB1:
	.cfi_startproc
	endbr64	
# main.cpp:5: int func2() { return other(233); }
	movl	$233, %edi	#,
	jmp	_Z5otheri@PLT	#
	.cfi_endproc
.LFE1:
	.size	_Z5func2v, .-_Z5func2v
	.ident	"GCC: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0"
	.section	.note.GNU-stack,"",@progbits
	.section	.note.gnu.property,"a"
	.align 8
	.long	1f - 0f
	.long	4f - 1f
	.long	5
0:
	.string	"GNU"
1:
	.align 8
	.long	0xc0000002
	.long	3f - 2f
2:
	.long	0x3
3:
	.align 8
4:
